theme: jekyll-theme-cayman
show_downloads: false
description: The goal for my blog is to practice my English writing and write my understanding when reading the paper. Thank you for your watching and 150%+ is better when reading the blog because the bad rendering of the mathmatical formula.
